version: '3.9'
name: keycloak-auth-setup
services:
  mysql-dev:
    image: mysql:latest
    restart: no
    ports:
      - '3307:3306'
    volumes:
      - mysql_db_data:/var/lib/mysql
    networks:
      keycloak-network:
    environment:
      - MYSQL_USER=keycloak-demo
      - MYSQL_DATABASE=keycloak-demo
      - MYSQL_ROOT_PASSWORD=keycloak-demo
      - MYSQL_PASSWORD=keycloak-demo
    container_name: mysql-dev

  keycloak-dev:
    image: my-keycloak-theme:latest
    restart: no
    command: start-dev
    depends_on:
      - mysql-dev
    ports:
      - '8080:8080'
    networks:
      keycloak-network:
    environment:
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - 'KC_DB_URL=jdbc:mysql://mysql-dev:3306/keycloak-demo'
      - KC_DB=mysql
      - KC_DB_PASSWORD=keycloak-demo
      - KC_DB_USERNAME=keycloak-demo
    container_name: keycloak-dev

  nginx-keycloak-dev:
    image: 'nginx:stable-alpine3.20-perl'
    restart: no
    ports:
      - '90:80'
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'
    networks:
      keycloak-network:
    container_name: nginx-keycloak-dev

networks:
  keycloak-network: {}

volumes:
  mysql_db_data:
